### ISSUE TITLE
Directory Restriction

### ISSUE THREAD

**Issue by jonprints** [tooll3/t3#343]
This isn't a huge issue, and I imagine it will likely only affect a small number of people, if any at all.. Maybe I'm the only one... :)

I use a specific directory that I created for portable programs, '/Program Files - Portable/'. When adding Tooll3 there, a dialog appears stating that I cannot run it in '/Program FIles/'. 

I can just put it in a different directory, it's seriously not a big issue. I just thought I'd notify you guys about it. I suppose specifically naming 'Program Files' and 'Program Files (x86)' as off limits instead of a directory containing the words would work out if it makes sense to do so...

Cheers!

**Comment by pixtur** [comment]
Thanks for the feedback! Sadly, people installing tooll by unzipping it to "Program Files" is a top reason for crashes. That's why we added that check in the first place. I spent some time into another check, but unless we have a proper installer (yes, we need that) it's not easy to detect whether tooll was installed into a read only directory.

I will close this issue for now. If somebody else stumbles across this, please reopen it!
